### ISSUE TITLE
GitHub Action Template

### ISSUE THREAD

**Issue by Snider** [lethean-io/build#3]
# task
Add config for GH Action to add the CC cmake build's

Documentation: [Publishing Actions in GitHub Marketplace](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace)

# why
I think it would be cool to have a GH Action that mapped [GH Action template inputs](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)

to link dynamically to, target + extras: https://github.com/letheanVPN/build-template/blob/main/.build/Makefile

https://github.com/letheanVPN/build-template/tree/main/.build/Makefile

Could be a location for this dynamic(ish) makefile exposing https://hub.docker.com/r/lthn/build/tags these, as `lthn/*` is under OS licence.

**Comment by RishiKumarRay** [comment]
Can you elaborate what we have to do? please

**Comment by Snider** [comment]
> Can you elaborate what we have to do? please

Sure, few moments.
